#!/usr/bin/env bash

echo "Time to update!"

display_usage() {
    echo
    echo "Usage: $0"
    echo "-h, --help   Display usage instructions"
    echo "-p, --print  Print welcome message"
}

print_message() {
    echo
    echo "Manage packages and installations from your package managers."
    echo
}

raise_error() {
    local error_message="$*"
    echo "${error_message}" 1>&2
}

arguments="$1"

if [[ -z $argument ]]; then
    raise_error "Argument needed"
    display_usage
else
    case $argument in
    -h | --help)
        display_usage
        ;;
    -p | --print)
        print_message
        ;;
    *) ;;
    esac
fi
