#!/usr/bin/env bash


# colors (bright)
B="$(echo -e "\e[1m")"      # bold
BL="$(echo -e "\e[94m")"    # blue
RCB="$(echo -e "\e[0;1m")"  # reset and continue bold
END="$(echo -e "\e[0m")"    # end (reset)


display_usage() {
    echo
    echo "Usage: $0"
    echo "-h,  Display usage instructions"
    echo "-b,  Update Homebrew"
    echo "-n,  Update npm packages"
    echo "-c,  Update conda packages"
    echo
    echo "Example usage: 
        update -b   //  brew update
        update -n   //  npm update -g
        update -nc  //  npm update -g ; conda update all"
}

   
raise_error() {
    local error_message="$*"
    echo "${error_message}" 1>&2
}

up_brew() {
    echo
    echo -e "${B}Updating ${BL}Homebrew${RCB} packages"\
        "[${BL}brew update${RCB}]${END}"
    echo
    brew update
}

up_npm() {
    echo
    echo -e "${B}Updating ${BL}npm${RCB} packages"\
        "[${BL}npm update -g${RCB}]${END}"
    echo
    npm update -g
}

up_conda() {
    echo
    echo -e "${B}Updating ${BL}conda${RCB} and conda packages"\
        "[${BL} conda update --all${RCB}]${END}"
    echo
    conda update --all
}


while getopts "hbnc" opt; do
   case ${opt} in
        (b)
            up_brew ;;
        (n)
            up_npm ;;
        (c)
            up_conda ;;
        (h)
            display_usage ;;
        (*) 
            raise_error "Invalid flag: $*" 
            echo "Usage: update [-h]" ;;
    esac
done

if [ "$#" == 0 ]; then
    display_usage
    exit 1
fi
 
