#!/usr/bin/env bash


# colors (bright)
B="$(echo -e "\e[1m")"      # bold
BL="$(echo -e "\e[94m")"    # blue
RCB="$(echo -e "\e[0;1m")"  # reset and continue bold
END="$(echo -e "\e[0m")"    # end (reset)


display_usage() {
    echo
    echo "Usage: $0"
    echo "   -h,  Display usage instructions"
    echo "   -b,  Update Homebrew"
    echo "   -n,  Update npm packages"
    echo "   -c,  Update conda packages"
    echo
    echo "Example usage: "
    echo "   update -b   //  brew update"
    echo "   update -n   //  npm update -g"
    echo "   update -nc  //  npm update -g ; conda update all"
}

   
raise_error() {
    local error_message="$*"
    echo "${error_message}" 1>&2
}

up_brew() {
    echo
    echo -e "${B}Updating ${BL}Homebrew${RCB} packages"\
        "[${BL}brew update${RCB}]${END}"
    echo
    brew update
}

up_npm() {
    echo
    echo -e "${B}Updating ${BL}npm${RCB} packages"\
        "[${BL}npm update -g${RCB}]${END}"
    echo
    npm update -g
}

up_conda() {
    echo
    echo -e "${B}Updating ${BL}conda${RCB} and conda packages"\
        "[${BL} conda update --all${RCB}]${END}"
    echo
    conda update --all
}


if [[ -z "$1" ]]; then
    display_usage
else
    for arg do
        #shift
        case $arg in
            (-b | --brew | "brew")
                up_brew
        #        shift
                ;;
            (-n | --npm | "npm")
                up_npm
        #        shift
                ;;
            (-c | --conda | "conda")
                up_conda
        #        shift
                ;;
            (*)
                raise_error "Unknown argument: ${arg}"
                display_usage
                exit 1
                ;;
        esac
    done
fi



