syntax on
set whichwrap+=<,>,h,l,[,]
set backspace=indent,eol,start
set mouse=nicr
set background=dark
" other colorschemes i like: abstract, afterglow, deep-space,
"                            atom, challenger_deep, molokayo,
"                            nord, dracula
"
"
"


" win alt key
set winaltkeys=no


nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
map <A-o> :NERDTreeToggle<CR>



set splitbelow
set splitright

set nu
set numberwidth=1
set smartcase
set laststatus=2
set noshowmode


filetype plugin indent on
filetype on
set smartindent
set tabstop=4
set shiftwidth=2
set expandtab
set autoindent


" plugins using vim-plug
call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'

Plug 'jiangmiao/auto-pairs'

Plug 'nathanaelkane/vim-indent-guides'

Plug 'terryma/vim-multiple-cursors'

Plug 'tpope/vim-eunuch'

Plug 'scrooloose/nerdtree'

Plug 'aonemd/kuroi.vim'

Plug 'ntk148v/vim-horizon'

Plug 'flazz/vim-colorschemes'

call plug#end()

colorscheme anderson

let g:indentLine_setColors = 0
let g:lightline = {
      \ 'colorscheme': '16color'
      \ }

let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1
let NERDTreeShowHidden=1



