#!/usr/bin/env bash


[[ -d "/Library/Frameworks/R.framework/Resources/lib" ]] \
    && cd "/Library/Frameworks/R.framework/Resources/lib" \
    || exit

ln -sf  "/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Versions/Current/libLAPACK.dylib" "libRlapack.dylib"

ln -sf  "/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Versions/Current/libBLAS.dylib" "libRblas.dylib"
